In [6]:
#Variáveis Catagóricas
import pandas as pd
import numpy as np

bs = pd.read_csv('database.csv', delimiter=';')
X = bs.iloc[:,:-1].values
y = bs.iloc[:,-1].values
print("Matriz X")
print(X)
print("\n")
print("Matriz y")
print(y)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
imputer = imputer.fit_transform(X[:,1:])
print("\n\n")
print("Matriz X")
print(X);


from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print("\n\n")
print("Matriz X com a coluna um modificada em ID")
print(X)

D = pd.get_dummies(X[:, 0])
X = X[:,1:]
X = np.insert(X, 0, D.values, axis = 1)
print("\n\n")
print("Matriz X com IDs modificados para Binários")
print(X)

Matriz X
[['Matheus' 10 5 4 10]
 ['Ramos' 7 8 9 10]
 ['Ferreira' 3 4 10 5]
 ['Silva' 2 1 7 9]
 ['Theus' 3 10 10 9]]


Matriz y
[1 1 0 0 1]



Matriz X
[['Matheus' 10 5 4 10]
 ['Ramos' 7 8 9 10]
 ['Ferreira' 3 4 10 5]
 ['Silva' 2 1 7 9]
 ['Theus' 3 10 10 9]]



Matriz X com a coluna um modificada em ID
[[1 10 5 4 10]
 [2 7 8 9 10]
 [0 3 4 10 5]
 [3 2 1 7 9]
 [4 3 10 10 9]]



Matriz X com IDs modificados para Binários
[[0 0 1 0 0 10 5 4 10]
 [1 0 0 0 0 7 8 9 10]
 [0 1 0 0 0 3 4 10 5]
 [0 0 0 1 0 2 1 7 9]
 [0 0 0 0 1 3 10 10 9]]


In [13]:
#Separação em Teste e Treino
import pandas as pd
import numpy as np

bs = pd.read_csv('database.csv', delimiter=';')
X = bs.iloc[:,:-1].values
y = bs.iloc[:,-1].values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
imputer = imputer.fit_transform(X[:,1:])


from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

D = pd.get_dummies(X[:, 0])
X = X[:,1:]
X = np.insert(X, 0, D.values, axis = 1)

#Parte que faz a Separação em Teste e Treino
from sklearn.model_selection import train_test_split
XTrein, XTest, yTrain, yTest = train_test_split(X, y, test_size = 0.2)
print("\n\n")
print("Matriz XTrein")
print(XTrein)
print("\n")
print("Matriz XTest")
print(XTest)
print("\n")
#print("Matriz yTrein")
#print(yTrein)
#print("\n")
#print("Matriz yTest")
#print(yTest)
#print("\n")




Matriz XTrein
[[0 1 0 0 0 3 4 10 5]
 [1 0 0 0 0 7 8 9 10]
 [0 0 1 0 0 10 5 4 10]
 [0 0 0 1 0 2 1 7 9]]


Matriz XTest
[[0 0 0 0 1 3 10 10 9]]


